<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE j01printserver-config [

<!ELEMENT j01printserver-config (system, datasource, device-list, applicationserver-notifica+)>
<!ATTLIST j01printserver-config	
                        listenPort              CDATA  "8889"
                        listenBackLog           CDATA  "500"
                        forcedPollingMillis     CDATA  "5000"
                        rinnovaWebConfigMillis	CDATA  "180000"
                        serverVersion           CDATA  "2"
                        disabilitaAcrobat       (true | false)	"true">

<!--
listenBackLog: dimensione della coda di attesa sulla porta in cui il servizio
               riceve le notifiche dall'application server di stampa pronta
               per essere eseguita
serverVersion: 1 = versione classica di PrintServer
               2 = versione con code di stampa e gestori (Java 1.6)
-->

<!ELEMENT applicationserver-notifica (#PCDATA)>

<!ELEMENT system (host, username, password)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>

<!ELEMENT datasource (set-property*)>
<!ATTLIST datasource	class			CDATA		"com.ibm.as400.access.AS400JDBCDataSource">
<!ELEMENT set-property	EMPTY>
<!ATTLIST set-property	property		CDATA		#REQUIRED
 						value			CDATA		#REQUIRED>


<!ELEMENT device-list (device+)>
<!ELEMENT device (device-config+)>
<!ATTLIST device		name			ID			#REQUIRED>
<!ELEMENT device-config (#PCDATA)>
<!ATTLIST device-config	param			CDATA		#REQUIRED>

]>

<j01printserver-config>
  <system>
    <host>host ip</host>
    <username>user</username>
    <password>pass</password>
  </system>
  <datasource>
    <set-property property="user" value="user"/>
    <set-property property="password" value="pass"/>
    <set-property property="serverName" value="ipaddress"/>
    <set-property property="libraries" value="libraries libraries"/>
    <set-property property="description" value="description"/>
    <set-property property="naming" value="system"/>
  </datasource>

  	<device-list>
	</device-list>
	<!-- <applicationserver-notifica>http://localhost:9080/j01smb_p/</applicationserver-notifica> -->
    <!-- <applicationserver-notifica>http://localhost:9082/j01smb_p/</applicationserver-notifica> -->
	<!-- <applicationserver-notifica>http://10.7.3.35:9080/j01smb_p/</applicationserver-notifica> ulteriori application server con cui sincronizzarsi -->
</j01printserver-config>
